# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(385, 480)
        MainWindow.setStyleSheet("background-color: rgb(62, 62, 62);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.answer_frame = QtWidgets.QFrame(self.centralwidget)
        self.answer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.answer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.answer_frame.setObjectName("answer_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.answer_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.answerLabel = QtWidgets.QLabel(self.answer_frame)
        self.answerLabel.setMinimumSize(QtCore.QSize(360, 80))
        self.answerLabel.setMaximumSize(QtCore.QSize(360, 80))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.answerLabel.setFont(font)
        self.answerLabel.setStyleSheet("background-color: rgb(158, 158, 158);\n"
"color: rgb(255, 255, 255);")
        self.answerLabel.setObjectName("answerLabel")
        self.verticalLayout_2.addWidget(self.answerLabel)
        self.verticalLayout.addWidget(self.answer_frame, 0, QtCore.Qt.AlignHCenter)
        self.buttoons_frame = QtWidgets.QFrame(self.centralwidget)
        self.buttoons_frame.setMinimumSize(QtCore.QSize(360, 360))
        self.buttoons_frame.setMaximumSize(QtCore.QSize(360, 360))
        self.buttoons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttoons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttoons_frame.setObjectName("buttoons_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.buttoons_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.but_plus = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_plus.setMinimumSize(QtCore.QSize(90, 90))
        self.but_plus.setMaximumSize(QtCore.QSize(90, 90))
        self.but_plus.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_plus.setObjectName("but_plus")
        self.gridLayout.addWidget(self.but_plus, 0, 6, 1, 1)
        self.but_6 = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_6.setMinimumSize(QtCore.QSize(90, 90))
        self.but_6.setMaximumSize(QtCore.QSize(90, 90))
        self.but_6.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_6.setObjectName("but_6")
        self.gridLayout.addWidget(self.but_6, 2, 4, 1, 1)
        self.but_8 = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_8.setMinimumSize(QtCore.QSize(90, 90))
        self.but_8.setMaximumSize(QtCore.QSize(90, 90))
        self.but_8.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_8.setObjectName("but_8")
        self.gridLayout.addWidget(self.but_8, 0, 2, 1, 1)
        self.but_5 = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_5.setMinimumSize(QtCore.QSize(90, 90))
        self.but_5.setMaximumSize(QtCore.QSize(90, 90))
        self.but_5.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_5.setObjectName("but_5")
        self.gridLayout.addWidget(self.but_5, 2, 2, 1, 1)
        self.but_9 = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_9.setMinimumSize(QtCore.QSize(90, 90))
        self.but_9.setMaximumSize(QtCore.QSize(90, 90))
        self.but_9.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_9.setObjectName("but_9")
        self.gridLayout.addWidget(self.but_9, 0, 4, 1, 1)
        self.but_7 = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_7.setMinimumSize(QtCore.QSize(90, 90))
        self.but_7.setMaximumSize(QtCore.QSize(90, 90))
        self.but_7.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_7.setObjectName("but_7")
        self.gridLayout.addWidget(self.but_7, 0, 0, 1, 1)
        self.but_1 = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_1.setMinimumSize(QtCore.QSize(90, 90))
        self.but_1.setMaximumSize(QtCore.QSize(90, 90))
        self.but_1.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_1.setObjectName("but_1")
        self.gridLayout.addWidget(self.but_1, 3, 0, 1, 1)
        self.but_equal = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_equal.setMinimumSize(QtCore.QSize(90, 90))
        self.but_equal.setMaximumSize(QtCore.QSize(90, 90))
        self.but_equal.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_equal.setObjectName("but_equal")
        self.gridLayout.addWidget(self.but_equal, 5, 6, 1, 1)
        self.but_division = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_division.setMinimumSize(QtCore.QSize(90, 90))
        self.but_division.setMaximumSize(QtCore.QSize(90, 90))
        self.but_division.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_division.setObjectName("but_devision")
        self.gridLayout.addWidget(self.but_division, 5, 4, 1, 1)
        self.but_0 = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_0.setMinimumSize(QtCore.QSize(90, 90))
        self.but_0.setMaximumSize(QtCore.QSize(90, 90))
        self.but_0.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_0.setObjectName("but_0")
        self.gridLayout.addWidget(self.but_0, 5, 0, 1, 1)
        self.but_dot = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_dot.setMinimumSize(QtCore.QSize(90, 90))
        self.but_dot.setMaximumSize(QtCore.QSize(90, 90))
        self.but_dot.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_dot.setObjectName("but_dot")
        self.gridLayout.addWidget(self.but_dot, 5, 2, 1, 1)
        self.but_minus = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_minus.setMinimumSize(QtCore.QSize(90, 90))
        self.but_minus.setMaximumSize(QtCore.QSize(90, 90))
        self.but_minus.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_minus.setObjectName("but_minus")
        self.gridLayout.addWidget(self.but_minus, 2, 6, 1, 1)
        self.but_4 = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_4.setMinimumSize(QtCore.QSize(90, 90))
        self.but_4.setMaximumSize(QtCore.QSize(90, 90))
        self.but_4.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_4.setObjectName("but_4")
        self.gridLayout.addWidget(self.but_4, 2, 0, 1, 1)
        self.but_multiply = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_multiply.setMinimumSize(QtCore.QSize(90, 90))
        self.but_multiply.setMaximumSize(QtCore.QSize(90, 90))
        self.but_multiply.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_multiply.setObjectName("but_multiply")
        self.gridLayout.addWidget(self.but_multiply, 3, 6, 1, 1)
        self.but_3 = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_3.setMinimumSize(QtCore.QSize(90, 90))
        self.but_3.setMaximumSize(QtCore.QSize(90, 90))
        self.but_3.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_3.setObjectName("but_3")
        self.gridLayout.addWidget(self.but_3, 3, 4, 1, 1)
        self.but_2 = QtWidgets.QPushButton(self.buttoons_frame)
        self.but_2.setMinimumSize(QtCore.QSize(90, 90))
        self.but_2.setMaximumSize(QtCore.QSize(90, 90))
        self.but_2.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier New\";")
        self.but_2.setObjectName("but_2")
        self.gridLayout.addWidget(self.but_2, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.buttoons_frame, 0, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_funtions()
        self.is_equal = False
        self.prevAns = ''

    def add_funtions(self):
        self.but_0.clicked.connect(lambda: self.write_number(self.but_0.text()))
        self.but_1.clicked.connect(lambda: self.write_number(self.but_1.text()))
        self.but_2.clicked.connect(lambda: self.write_number(self.but_2.text()))
        self.but_3.clicked.connect(lambda: self.write_number(self.but_3.text()))
        self.but_4.clicked.connect(lambda: self.write_number(self.but_4.text()))
        self.but_5.clicked.connect(lambda: self.write_number(self.but_5.text()))
        self.but_6.clicked.connect(lambda: self.write_number(self.but_6.text()))
        self.but_7.clicked.connect(lambda: self.write_number(self.but_7.text()))
        self.but_8.clicked.connect(lambda: self.write_number(self.but_8.text()))
        self.but_9.clicked.connect(lambda: self.write_number(self.but_9.text()))
        self.but_plus.clicked.connect(lambda: self.write_number(self.but_plus.text()))
        self.but_minus.clicked.connect(lambda: self.write_number(self.but_minus.text()))
        self.but_division.clicked.connect(lambda: self.write_number(self.but_division.text()))
        self.but_multiply.clicked.connect(lambda: self.write_number(self.but_multiply.text()))
        self.but_dot.clicked.connect(lambda: self.write_number(self.but_dot.text()))
        self.but_equal.clicked.connect(self.solve)

    def write_number(self,  num):
        if self.answerLabel.text() == "0" or self.is_equal:
            self.answerLabel.setText(num)
            self.is_equal = False
        else:
            self.answerLabel.setText(self.answerLabel.text() + num)

    def solve(self):
        if(self.answerLabel.text()!=self.prevAns):
            try:
                res = eval(self.answerLabel.text())
                self.answerLabel.setText("Result: " + str(res))
            except:
                self.answerLabel.setText("ERROR")
            finally:
                self.prevAns = self.answerLabel.text()
                self.is_equal = True

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.answerLabel.setText(_translate("MainWindow", "0"))
        self.but_plus.setText(_translate("MainWindow", "+"))
        self.but_6.setText(_translate("MainWindow", "6"))
        self.but_8.setText(_translate("MainWindow", "8"))
        self.but_5.setText(_translate("MainWindow", "5"))
        self.but_9.setText(_translate("MainWindow", "9"))
        self.but_7.setText(_translate("MainWindow", "7"))
        self.but_1.setText(_translate("MainWindow", "1"))
        self.but_equal.setText(_translate("MainWindow", "="))
        self.but_division.setText(_translate("MainWindow", "/"))
        self.but_0.setText(_translate("MainWindow", "0"))
        self.but_dot.setText(_translate("MainWindow", "."))
        self.but_minus.setText(_translate("MainWindow", "-"))
        self.but_4.setText(_translate("MainWindow", "4"))
        self.but_multiply.setText(_translate("MainWindow", "*"))
        self.but_3.setText(_translate("MainWindow", "3"))
        self.but_2.setText(_translate("MainWindow", "2"))


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        QtWidgets.QMainWindow.__init__(self, parent=parent)
        self.setupUi(self)

    def keyPressEvent(self, e):
        if type(e) == QtGui.QKeyEvent:
            if e.key() == QtCore.Qt.Key.Key_0:
                self.write_number("0")
            if e.key() == QtCore.Qt.Key.Key_1:
                self.write_number("1")
            if e.key() == QtCore.Qt.Key.Key_2:
                self.write_number("2")
            if e.key() == QtCore.Qt.Key.Key_3:
                self.write_number("3")
            if e.key() == QtCore.Qt.Key.Key_4:
                self.write_number("4")
            if e.key() == QtCore.Qt.Key.Key_5:
                self.write_number("5")
            if e.key() == QtCore.Qt.Key.Key_6:
                self.write_number("6")
            if e.key() == QtCore.Qt.Key.Key_7:
                self.write_number("7")
            if e.key() == QtCore.Qt.Key.Key_8:
                self.write_number("8")
            if e.key() == QtCore.Qt.Key.Key_9:
                self.write_number("9")
            if e.key() == QtCore.Qt.Key.Key_Plus:
                self.write_number("+")
            if e.key() == QtCore.Qt.Key.Key_Minus:
                self.write_number("-")
            if e.key() == QtCore.Qt.Key.Key_Asterisk:
                self.write_number("*")
            if e.key() == QtCore.Qt.Key.Key_Slash:
                self.write_number("/")
            if e.key() == QtCore.Qt.Key.Key_Period:
                self.write_number(".")
            if e.key() == QtCore.Qt.Key.Key_Enter:
                self.solve()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = MainWindow()
    mainWindow.show()
    sys.exit(app.exec_())
